ALTER TABLE `Product` DROP FOREIGN KEY `Product_fk0`;

ALTER TABLE `Product` DROP FOREIGN KEY `Product_fk1`;

ALTER TABLE `Order` DROP FOREIGN KEY `Order_fk0`;

DROP TABLE IF EXISTS `Shop`;

DROP TABLE IF EXISTS `Product`;

DROP TABLE IF EXISTS `Category`;

DROP TABLE IF EXISTS `Order`;

DROP TABLE IF EXISTS `Page`;

